# Generated by Django 2.2.5 on 2019-10-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_ow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coord',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='coord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cities.Coord'),
        ),
    ]
